### ISSUE TITLE
yardim.setcrm.com da 753 benzer link bulma sorunu

### ISSUE THREAD

**Issue by kemalcolak** [argeset/setcrm.com#11]
moz önerisine göre buradaki linkler problem. 

yardim.setcrm.com link görünümünde ise seçili olan ayarın SEO için en iyi olduğunu söylüyor. 

![image](https://cloud.githubusercontent.com/assets/6229389/8719107/ce702bd6-2bb1-11e5-8ac8-4258d8de8baf.png)

Bunu nasıl aşabiliriz.?

http://analytics.moz.com/search/crawl-issues/4214207.961056?issue=duplicate_page_content#high

kemal@argeset.com

Arge+-2014

**Comment by kemalcolak** [comment]
ayrıca duplicated content problemide var

http://analytics.moz.com/search/crawl-issues/4214207.961056?issue=duplicate_page_title#medium

**Comment by salihangun** [comment]
![image](https://cloud.githubusercontent.com/assets/9803257/8771088/33709604-2ec5-11e5-8814-5ae56a711360.png)


![image](https://cloud.githubusercontent.com/assets/9803257/8771058/b109dc0c-2ec4-11e5-826e-e1d3c598d308.png)

üye olmadan yardım.setcrm.com a soru sorulamadıgı için bütün linkler register den gidiyor. buna yapabileceğimiz birşey yok gibi
